
title: FANTASTIC FIVE
url: 'https://fantastic-five-18.github.io/'
baseurl: '/driveway_weather_app2' #change it according to your repository name



# User information
yourname: UserName LastName  ## put your name
title: 'SOMETHING ABOUT USER'  ## your title
location: Detroit , MI


## Social team
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
